# Site settings
title: Elegant
email: eleganthaar@gmail.com
url: http://elegantliedekerke.be
description: "Elegant Liedekerke verzorgt de haartooi van zowel mannen, vrouwen en kinderen.
Ook voor gelnagels,nagelversteviging, manicure en pedicure kan u bij ons terecht."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-light: '#fff'
  primary-dark: '#4b4b4b'
  links: '#ff3680'

# Footer settings
footer: Elegant

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
facebook:
  url: https://www.facebook.com/ElegantHaarNagelstudio/
instagram:
  url: https://www.instagram.com/vicky_elegant_haar_en_nagels/

# External booking link to make appointments
bookingurl: https://elegantliedekerke.posworld.be/

# Build settings
markdown: kramdown
permalink: pretty
include: ['_pages']